In real life we most likely have fetch calls or API calls that are asynchronous. Thats what asynchronous tests face to.

### Useful APIs

Heads up! In the next video, I am going to introduce you to an API endpoint that sometime may or may not be available (SWAPI API). To make sure you are still able to run the code properly, I have added a few other options for you to use so that you make sure the API endpoint we will be testing works. You can use any of the below APIs that work in the next video:

I recommend using: [**http://swapi.py4e.com/api/people**](http://swapi.py4e.com/api/people/)

[**Star Wars API**](http://swapi.py4e.com/) **or** [**Star Wars API (clone)**](https://swapi.dev/)

[**Numbers API**](http://numbersapi.com/#42)

[**Chuck Norris API**](https://api.chucknorris.io/)

[**Pokemon API**](https://pokeapi.co/)

------

In node environment there is not a `window` object like in the browser.

```shell
npm install node-fetch
```

### script2.js

```js
const fetch = require('node-fetch');

const getPeoplePromise = fetch => {
	return fetch('http://swapi.py4e.com/api/people')
		.then(response => response.json())
		.then(data => {
    //console.log(data);
			return {
				count: data.count,
				results: data.results
			}
		})
}

//Async await way:
const getPeople = async (fetch) => {
	const getRequest = await fetch('http://swapi.py4e.com/api/people')
  const data = await getRequest.json();
  //console.log(data);
  return {
		count: data.count,
		results: data.results
	}
}

//getPeople(fetch)

module.exports = {
  getPeople,
  getPeoplePromise
}
```

```shell
node script2.js
```

### script2.test.js

```js
const fetch = require('node-fetch')
const swapi = require('./script2')

//Problem:
it('calls swapi to get people', () => {
  //assertions(1) tells Jest we expect to see 1 assertion called, if the code doesn't check, it will show error.
  expect.assertions(1)
  swapi.getPeople(fetch).then(data => {
    //Because this is in a promise, the code get returned before we receive the data, the assertion below will not run. Without expect.assertions(1), the test will be passed anyway, now it will show failed
		expect(data.count).toEqual(87)
  })
})

//Solution 1:
//pass in a "done" to let test wait until "done" been runned
it('calls swapi to get people', (done) => {
  expect.assertions(1)
  swapi.getPeople(fetch).then(data => {
		expect(data.count).toEqual(87)
    done();
  })
})

//Solution 2 (easy way):
//return the promise, so that it will wait to see the results returned
it('calls swapi to get people', () => {
  expect.assertions(1)
  return swapi.getPeople(fetch).then(data => {
		expect(data.count).toEqual(87)
  })
})

it('calls swapi to get people with a promise', () => {
  expect.assertions(2)
  return swapi.getPeoplePromise(fetch).then(data => {
		expect(data.count).toEqual(87);
    expect(data.results.length).toBeGreaterThan(5)
  })
})
```

```shell
npm test
```

#### **Note: When do asynchronous test, ALWAYS uses `expect.assertions()`**



